# Generated by Django 5.0.2 on 2024-04-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'permissions': [('set_published', 'Can publish products'), ('change_description', 'Can change description'), ('change_category', 'Can change category')], 'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
    ]
